### PR TITLE
new: Support pricing for LKE, Volume, NodeBalancer and Network Transfer

### PR DESCRIPTION
**Pull request by yec-akamai**
## 📝 Description

Add support for the following pricing endpoints:

- https://api.linode.com/v4/lke/types
- https://api.linode.com/v4/nodebalancers/types
- https://api.linode.com/v4/volumes/types
- https://api.linode.com/v4/network-transfer/prices

## ✔️ How to Test

Unit test: 

```
make testunit
```

Integration tests:

```
make testint TEST_COMMAND="models/volume"
make testint TEST_COMMAND="models/networking"
make testint TEST_COMMAND="models/lke"
make testint TEST_COMMAND="models/nodebalancer"
```

### CODE REVIEW

**Review by ezilber-akamai — APPROVED** [review]
Test passing locally! Are the `TODOs` for API Documentation there because there aren't tech docs pages for these endpoints yet?

**Comment by yec-akamai** [comment]
> Test passing locally! Are the `TODOs` for API Documentation there because there aren't tech docs pages for these endpoints yet?

Yep I didn't find these new endpoints in the tech doc

**Review by ykim-1 — APPROVED** [review]
LGTM, slightly added more details to integration tests. Nice work!

**Comment by yec-akamai** [comment]
> LGTM, slightly added more details to integration tests. Nice work!

Thank you for adding the integration tests! They looks perfect and work well on my end 🎉

**Pull request merged**
