### PR TITLE
Serialize `Base` objects in `MappedObject`

### PR DESCRIPTION
**Pull request by zliang-akamai**
## 📝 Description

Convert nested `Base` objects in a `MappedObject` to dict in the `dict` property of `MappedObject`.

This can prevent exception of `TypeError: Object of type SomeBaseType is not JSON serializable` when passing the `dict` property of a `MappedObject` into the json library for serializing.

### Automated Testing
```bash
make testunit
```

### Manual Testing
```python
import os
from linode_api4 import LinodeClient

client = LinodeClient(os.getenv("LINODE_TOKEN"))

instance, _ = client.linode.instance_create(
    ltype="g6-nanode-1",
    region="us-mia",
    image="linode/ubuntu22.04",
    label="my-ubuntu-linode"
)

print(instance.ips.dict)

```

##### Before (dev branch)

```
{
    "ipv4": {
        "public": [IPAddress: 172.233.181.127],
        "private": [],
        "shared": [],
        "reserved": [],
        "vpc": [],
    },
    "ipv6": {
        "slaac": IPAddress: 2a01:7e04::f03c:94ff:fe72:159a,
        "link_local": IPAddress: fe80::f03c:94ff:fe72:159a,
        "ranges": [],
    },
}
```

##### After

```python
{
    "ipv4": {
        "public": [
            {
                "address": "172.233.181.52",
                "gateway": "172.233.181.1",
                "subnet_mask": "255.255.255.0",
                "prefix": 24,
                "type": "ipv4",
                "public": True,
                "rdns": "172-233-181-52.ip.linodeusercontent.com",
                "linode_id": 56675621,
                "region": "us-mia",
                "vpc_nat_1_1": None,
            }
        ],
        "private": [],
        "shared": [],
        "reserved": [],
        "vpc": [],
    },
    "ipv6": {
        "slaac": {
            "address": "2a01:7e04::f03c:94ff:fe72:158f",
            "gateway": "fe80::1",
            "subnet_mask": "ffff:ffff:ffff:ffff::",
            "prefix": 64,
            "type": "ipv6",
            "rdns": None,
            "linode_id": 56675621,
            "region": "us-mia",
            "public": True,
        },
        "link_local": {
            "address": "fe80::f03c:94ff:fe72:158f",
            "gateway": "fe80::1",
            "subnet_mask": "ffff:ffff:ffff:ffff::",
            "prefix": 64,
            "type": "ipv6",
            "rdns": None,
            "linode_id": 56675621,
            "region": "us-mia",
            "public": False,
        },
        "ranges": [],
    },
}
```

### CODE REVIEW

**Review by lgarber-akamai — COMMENTED** [review]
@zliang-akamai This looks great, thanks for fixing this! Could you add a corresponding unit test?

**Review by lgarber-akamai — APPROVED** [review]
LGTM, nice work!

**Review by yec-akamai — APPROVED** [review]
Nice work! Works well on my end

**Review by jriddle-linode — APPROVED** [review]
LGTM

**Pull request merged**
