### PR TITLE
Project: Image Services Gen2

### PR DESCRIPTION
**Pull request by yec-akamai**
## 📝 Description

Project Image Gen2 LA

```
make testint TEST_SUITE=linode_client
```
```
make testint TEST_SUITE=image
```

### CODE REVIEW

**Review by ezilber-akamai — COMMENTED** [review]
I got an error when running `make testint TEST_SUITE=linode_client` locally. It doesn't seem to be related to the changes though. I tried in a different branch and saw the same error.
```
_______________________________________________________________________________________ test_get_account_settings _______________________________________________________________________________________

test_linode_client = <linode_api4.linode_client.LinodeClient object at 0x104a0f100>

    def test_get_account_settings(test_linode_client):
        client = test_linode_client
        account_settings = client.account.settings()
    
        assert account_settings._populated == True
>       assert re.search(
            "'network_helper':True|False", str(account_settings._raw_json)
        )
E       assert None
E        +  where None = <function search at 0x102ac54c0>("'network_helper':True|False", "{'managed': True, 'network_helper': True, 'longview_subscription': 'longview-100', 'backups_enabled': True, 'object_storage': 'active'}")
E        +    where <function search at 0x102ac54c0> = re.search
E        +    and   "{'managed': True, 'network_helper': True, 'longview_subscription': 'longview-100', 'backups_enabled': True, 'object_storage': 'active'}" = str({'backups_enabled': True, 'longview_subscription': 'longview-100', 'managed': True, 'network_helper': True, ...})
E        +      where {'backups_enabled': True, 'longview_subscription': 'longview-100', 'managed': True, 'network_helper': True, ...} = AccountSettings: True._raw_json
```

**Comment by ezilber-akamai** [comment]
I'm also running into a 404 when running `make testint TEST_SUITE=image` but this is likely because the test isn't being run in the correct region. Is there some additional setup I need to do to run the test against the right region?

**Comment by yec-akamai** [comment]
> I'm also running into a 404 when running `make testint TEST_SUITE=image` but this is likely because the test isn't being run in the correct region. Is there some additional setup I need to do to run the test against the right region?

Interesting, I've hardcoded the region to be us-east and it should work. Do you have the customer tag we mentioned in the thread?

**Comment by lgarber-akamai** [comment]
@ezilber-akamai For the account settings test, I think the regex is looking for `'network_helper':True` or just `False`. I'm guessing this is causing a failure on your end since your account doesn't seem to have any disable settings.

I think the corrected pattern would look like this:
```regex
'network_helper':\s*(True|False)
```

**Comment by yec-akamai** [comment]
> If we don't want to include that fix in this PR since it's out of sc

Good point! I included this fix in the PR. Also I changed a bit the get random region function to make sure we only get core site for testing. Some of the functions are not available in non-core sites.

**Review by ezilber-akamai — APPROVED** [review]
Tests passing locally. Nice work!

**Review by ykim-1 — APPROVED** [review]

**Comment by ykim-1** [comment]
LGTM tests pass locally

**Pull request merged**
