### PR TITLE
proposal: Move all top-level methods to groups and correct documentation

### PR DESCRIPTION
**Pull request by lgarber-akamai**
## 📝 Description

This change moves all top-level methods (`LinodeClient.nodebalancers(...)`, etc.) to groups to ensure consistency with the rest of the project. Additionally, alias methods have been created to prevent introducing any breaking changes and to ensure backwards compatibility.

Top-level list methods are now implemented as `__call__(...)` methods for group classes, and create functions have been moved to `create(...)` methods inside of each group.

These groups have all been moved to a separate `groups` package which significantly reduces the size of the `linode_client` package.

This change also introduces a few fixes for documentation issues:
- The sidebar width has been slightly increased to prevent content on the sidebar from overlapping with page content
- The page width has been slightly increased to improve readability
- Groups that were previously missing from the documentation have since been added

## ✔️ How to Test

Testing refactor changes:
```bash
tox
```

Testing docs changes:
```bash
sphinx-autobuild docs docs/build
```

### CODE REVIEW

**Comment by lgarber-akamai** [comment]
I keep going back and forth on this idea. I like the idea of mimicking the API's actual structure as much as possible, but implementing only some top-level methods in the client class seems a bit confusing to me.

**Comment by lgarber-akamai** [comment]
I just pushed up an example I'm much happier with. I'd love to hear some thoughts 🙂

**Review by ezilber-akamai — APPROVED** [review]
Tests are passing locally! I think this is a much better structure for the project. It's less clunky and much easier to track down where changes should go. Good work!

**Review by yec-akamai — APPROVED** [review]
Great work! Once your change merged, I'll rebase it and refactor the obj group that I'm working on.

**Comment by lgarber-akamai** [comment]
Thanks everyone!

**Pull request merged**
