### PR TITLE
test: Add job in E2E CI to attach firewall to any remaining instances

### PR DESCRIPTION
**Pull request by ykim-akamai**
## 📝 Description

Adding `add-fw-to-remaining-instances` job to E2E CIs to ensure all remaining instances or nodes have CFW attached

## ✔️ How to Test

Passing on CLI integration workflow, the job is essentially the same - https://github.com/linode/linode-cli/actions/runs/11634047963

## 📷 Preview

**If applicable, include a screenshot or code snippet of this change. Otherwise, please remove this section.**

### CODE REVIEW

**Review by yec-akamai — COMMENTED** [review]
LGTM. Is the forked run available now?

**Comment by ykim-akamai** [comment]
> LGTM. Is the forked run available now?

Yeah I included the latest CLI run which includes essentially the same jobs after test execution

**Review by jriddle-linode — APPROVED** [review]
LGTM, firewalls everywhere!

**Review by yec-akamai — APPROVED** [review]
Nice work!

**Pull request merged**
